name: Build and Publish inkcpp for Godot 4.3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ninja

      - name: Clone inkcpp Repository
        run: git clone --recurse-submodules https://github.com/JBenda/inkcpp.git

      - name: Configure and Build with CMake
        run: |
          mkdir build
          cd build
          cmake ../inkcpp -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Check Build Output
        run: |
          echo "Checking contents of the build directory..."
          Get-ChildItem -Recurse build/

      - name: Prepare Plugin Directory
        run: |
          mkdir -p addons/inkcpp/bin
          copy build/*.dll addons/inkcpp/bin/
          
          # Create the inkcpp.gdextension file with correct format
          echo "[configuration]" > addons/inkcpp/inkcpp.gdextension
          echo "entry_symbol = \"inkcpp\"" >> addons/inkcpp/inkcpp.gdextension
          echo "" >> addons/inkcpp/inkcpp.gdextension
          echo "[libraries]" >> addons/inkcpp/inkcpp.gdextension
          echo "windows.64 = \"res://addons/inkcpp/bin/inkcpp.dll\"" >> addons/inkcpp/inkcpp.gdextension


      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: inkcpp-plugin
          path: addons/inkcpp/




